string recognitions3d_topic
int64 id                                  #local id on image (can come from detection or instance segmentation) (optional)
int64 global_id                           #global id to identify a description (optional)
string label                              #class detected by classification, detection, semantic segmentation or instance segmentation
float64 timeout
---