vision_language_model:
    ros__parameters:

        subscribers:
            image_rgb:
                topic: /cam1/color/image_raw
                timeout: 5
            question:
                topic: /fbot_vision/bvlm/question_answering/question
        
        publishers:
            answer:
                topic: /fbot_vision/bvlm/question_answering/answer

        servers:
            question_answering:
                service: /fbot_vision/bvlm/question_answering/query
            answer_history:
                service: /fbot_vision/bvlm/answer_history/query
