yolo_node:
  ros__parameters:
    model: yolov8n.pt
    device: cuda:0
    fuse_model: true
    yolo_encoding: bgr8
    enable: true
    image_reliability: 1
    threshold: 0.5
    iou: 0.7
    imgsz_height: 480
    imgsz_width: 640
    half: true
    max_det: 100
    augment: false
    agnostic_nms: false
    retina_masks: false

    subscribers:
      image_raw: /femtobolt/color/image_raw

    publishers:
      detections:
        topic: /fbot_vision/fr/object_recognition2D
      detections_3d:
        topic: /fbot_vision/femtobolt/object_recognition
      debug:
        topic: /fbot_vision/fr/object_debug

tracking_node:
  ros__parameters:
    tracker: bytetrack.yaml
    image_reliability: 1

    subscribers:
      image_raw: /femtobolt/color/image_raw
      detections: /fbot_vision/fr/object_recognition2D

    publishers:
      tracking:
        topic: /fbot_vision/fr/object_tracking

detect_3d_node:
  ros__parameters:
    target_frame: base_link
    depth_image_units_divisor: 1000
    depth_image_reliability: 1
    depth_info_reliability: 1
    enable_foreground_filter: true
    enable_bimodal_filter: true
    mask_erosion_ratio: 0.08
    bimodal_min_gap: 0.08
    max_depth_extent_default: 0.60
    max_depth_extent_bottle: 0.15

    subscribers:
      depth_image: /femtobolt/depth/image_raw
      depth_info: /femtobolt/depth/camera_info
      detections: /fbot_vision/fr/object_recognition2D

    publishers:
      detections_3d:
        topic: /fbot_vision/fr/object_recognition

debug_node:
  ros__parameters:
    image_reliability: 1
    use_3d: false

    subscribers:
      image_raw: /femtobolt/color/image_raw
      detections: /fbot_vision/fr/object_recognition2D

    publishers:
      debug:
        topic: /fbot_vision/fr/object_debug
